apiVersion: batch/v1
kind: Job
metadata:
  name: {{ index . "name" }}
  namespace: {{ index . "namespace" }}
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - echo
            - job succeed
          image: alpine/curl
          imagePullPolicy: Always
          name: job-completed
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sh
            - -c
            - mkdir -p /data/isos; curl -vvv {{ index . "imageUrl" }} -o /data/isos/{{ index . "imageName" }}
          image: alpine/curl
          imagePullPolicy: Always
          name: download-image
          volumeMounts:
            - mountPath: /data/
              name: {{ index . "name" }}-data
        - command:
            - omni-imager
            - edit
            - ks
            - --config-file
            - /etc/omni-imager/conf.yaml
            - --ks
            - /etc/omni-imager/ks.cfg
            - --iso
            - /data/isos/{{ index . "imageName" }}
            - --output-file
            - Customized-{{ index . "name" }}.iso
          image: tommylike/omni-worker:0.3.2
          imagePullPolicy: IfNotPresent
          name: build-image
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/omni-imager/conf.yaml
              name: {{ index . "name" }}-config
              subPath: conf.yaml
            - mountPath: /etc/omni-imager/ks.cfg
              name: {{ index . "name" }}-config
              subPath: ks.cfg
            - mountPath: /data/
              name: {{ index . "name" }}-data
            - mountPath: /dev/
              name: hostdevicevolume
          resources:
            requests:
              memory: "20480Mi"
              cpu: "1000m"
            limits:
              memory: "20480Mi"
              cpu: "1000m"
        - command:
            - curl
            - -vvv
            - -Ffile=@/data/omni-workspace/Customized-{{ index . "name" }}.iso
            - -Ftype={{ index . "type" }}
            - -FexternalID={{ index . "name" }}
            - -Fusername={{ index . "userID" }}
            - http://omni-repository.omni-repository.svc.cluster.local/data/upload?token=316462d0c029ba707ad2
          image: alpine/curl
          imagePullPolicy: Always
          name: upload-image
          volumeMounts:
            - mountPath: /data/
              name: {{ index . "name" }}-data
      restartPolicy: Never
      volumes:
        - name: hostdevicevolume
          hostPath:
            path: /dev
            type: Directory
        - configMap:
            defaultMode: 420
            name: {{ index . "name" }}
          name: {{ index . "name" }}-config
        - emptyDir:
            sizeLimit: 20G
            medium: Memory
          name: {{ index . "name" }}-data
  ttlSecondsAfterFinished: 1800
