apiVersion: batch/v1
kind: Job
metadata:
  name: {{ index . "name" }}
  namespace: {{ index . "namespace" }}
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - echo
            - job succeed
          image: alpine/curl
          imagePullPolicy: Always
          name: job-completed
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sh
            - -c
            - mkdir -p /data/isos; curl -vvv {{ index . "imageUrl" }} -o /data/isos/{{ index . "imageName" }}
          image: alpine/curl
          imagePullPolicy: Always
          name: download-iso
          volumeMounts:
            - mountPath: /data/
              name: {{ index . "name" }}-data
        - command:
            - sh
            - -c
            - mknod /dev/loop1001 b 7 1001;chown --reference=/dev/loop0 /dev/loop1001;chmod --reference=/dev/loop0 /dev/loop1001
          image: tommylike/omni-worker:0.3.1
          securityContext:
            privileged: true
          imagePullPolicy: Always
          name: prepare-loop-device
        - command:
            - omni-imager
            - edit ks
            - --config-file
            - /etc/omni-imager/conf.yaml
            - --ks
            -
            - --iso
            - /data/isos/{{ index . "imageName" }}
            - --output-file
            - Customized-{{ index . "name" }}.iso
          image: tommylike/omni-worker:0.3.1
          imagePullPolicy: IfNotPresent
          name: image-build
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/omni-imager/conf.yaml
              name: {{ index . "name" }}-config
              subPath: conf.yaml
            - mountPath: /etc/omni-imager/ks.cfg
              name: {{ index . "name" }}-config
              subPath: ks.cfg
            - mountPath: /data/
              name: {{ index . "name" }}-data
        - command:
            - curl
            - -vvv
            - -Ffile=@/data/omni-workspace/Customized-{{ index . "name" }}.iso
            - -Fproject=buildimagefromiso
            - -FfileType=image
            - -Fid={{ index . "name" }}
            - http://omni-repository.omni-repository.svc.cluster.local/data/upload?token=316462d0c029ba707ad2
          image: alpine/curl
          imagePullPolicy: Always
          name: image-upload
          volumeMounts:
            - mountPath: /data/
              name: {{ index . "name" }}-data
      restartPolicy: Never
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ index . "name" }}
          name: {{ index . "name" }}-config
        - emptyDir:
            sizeLimit: 20G
          name: {{ index . "name" }}-data
  ttlSecondsAfterFinished: 1800
