apiVersion: v1
kind: ConfigMap
metadata:
  name: omni-repository-config
data:
  app.toml: |
    name = "omni-orchestator"
    timezone = "PRC"
    httpPort = 8080

    [log]
    logFile = "/app/logs/run-application-{date}.log"
    errFile = "/app/logs/run-error-{date}.log"

    [manager]
    dataFolder = "/app/data/"
    uploadToken = "316462d0c029ba707ad1"
