apiVersion: v1
kind: ConfigMap
metadata:
  name: omni-orchestrator-config
data:
  app.toml: |
    name = "omni-orchestrator"
    [server]
    httpPort = 8080
    [log]
    logFile = "./logs/info-{date}.log"
    errFile = "./logs/error-{date}.log"
    [jobManager]
    worker = 3
    syncInterval = 3
    [logManager]
    worker = 6
    ttl = 2592000
    [engine]
    pluginName = "kubernetes"
    x86ConfigFile = ""
    aarch64ConfigFile = ""
    kubernetesTemplateFolder= "/app/config/templates"
    [persistentStore]
    pluginName = "cassandra"
    hosts = "omni-cassandra.omni-orchestrator.svc.cluster.local"
    port = 9042
    keyspace = "omni_orchestrator"
    protoVersion = 0