apiVersion: apps/v1
kind: Deployment
metadata:
  name: omni-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      component: omni-repository-server
  template:
    metadata:
      labels:
        component: omni-repository-server
    spec:
      containers:
        - image: tommylike/omni-repository:0.0.1
          imagePullPolicy: Always
          name: omni-repository-server
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 20
            failureThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: APP_ENV
              value: "prod"
            - name: UPLOAD_TOKEN
              value: "316462d0c029ba707ad2"
          volumeMounts:
            - mountPath: /app/data
              name: data-volume
            - mountPath: /app/config/app.toml
              name: config-volume
              subPath: app.toml
      serviceAccountName: omni-repository
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: omni-repository-data
        - name: config-volume
          configMap:
            name: omni-repository-config
