apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omni-repository-ingress
spec:
  rules:
    - host: repo.test.osinfra.cn
      http:
        paths:
          - backend:
              service:
                name: omni-repository
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - repo.test.osinfra.cn
      secretName: omni-repo-secret

