resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- config.yaml
- rbac.yaml
- pvc.yaml
- ingress.yaml
commonLabels:
  app: omni-orchestrator-server
  owner: tommylike
commonAnnotations:
  email: tommylikehu@gmail.com
namespace: omni-orchestrator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/omni-orchestrator
  newTag: d711cbbf31dce1f90727ea8ee7e259001cf65b64
