resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- config.yaml
- rbac.yaml
- pvc.yaml
- ingress.yaml
commonLabels:
  app: omni-orchestrator-server
  owner: tommylike
# used for job templates, update this when template files add or removed
configMapGenerator:
- files:
  - configmap.yaml=resources/buildimagefromrelease/configmap.yaml
  - job.yaml=resources/buildimagefromrelease/job.yaml
  name: omni-orchestrator-templates-buildimagefromrelease
commonAnnotations:
  email: tommylikehu@gmail.com
namespace: omni-orchestrator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/omni-orchestrator
  newTag: cae48c8096f236f600f40941c929dc3a34f62c46
