resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- config.yaml
- rbac.yaml
- pvc.yaml
- ingress.yaml
commonLabels:
  app: omni-orchestrator-server
  owner: tommylike
# used for job templates, update this when template files add or removed
# job: build image from official release
# job: build image from iso file
configMapGenerator:
- files:
  - configmap.yaml=resources/buildimagefromrelease/configmap.yaml
  - job.yaml=resources/buildimagefromrelease/job.yaml
  name: omni-orchestrator-templates-buildimagefromrelease
- files:
  - configmap.yaml=resources/buildimagefromiso/configmap.yaml
  - job.yaml=resources/buildimagefromiso/job.yaml
  name: omni-orchestrator-templates-buildimagefromiso
commonAnnotations:
  email: tommylikehu@gmail.com
namespace: omni-orchestrator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/omni-orchestrator
  newTag: 261ac7ed6bf88e810dcaa963b90eb1b1d6a5c7f0
