resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- config.yaml
- rbac.yaml
- pvc.yaml
- ingress.yaml
commonLabels:
  app: omni-orchestrator-server
  owner: tommylike
# used for job templates, update this when template files add or removed
configMapGenerator:
- files:
  - buildimagefromrelease-configmap.yaml=resources/buildimagefromrelease/configmap.yaml
  - buildimagefromrelease-job.yaml=resources/buildimagefromrelease/job.yaml
  name: omni-orchestrator-templates
commonAnnotations:
  email: tommylikehu@gmail.com
namespace: omni-orchestrator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/omni-orchestrator
  newTag: cfb76c605313c1de53615b2dfc6fd14b914acc8f
