---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omni-orchestrator-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: ssd

