apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: omni-orchestrator
rules:
  - apiGroups:
    - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
    verbs:
      - get
      - create
      - list
      - watch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: omni-orchestrator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: omni-orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: omni-orchestrator
subjects:
  - kind: ServiceAccount
    name: omni-orchestrator
