apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: omni-repository
rules: []
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: omni-repository
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: omni-repository
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: omni-repository
subjects:
  - kind: ServiceAccount
    name: omni-repository
