name = "omni-orchestrator"
[server]
httpPort = 8080
[log]
logFile = "./logs/info-{date}.log"
errFile = "./logs/error-{date}.log"
[jobManager]
worker = 3
syncInterval = 2
# job will save only 6 month
ttl = 15552000
[logManager]
worker = 5
# log will save only 1 month
ttl = 2592000
[engine]
pluginName = "kubernetes"
x86ConfigFile = "/Users/tommylike/.kube/infra-test.yaml"
aarch64ConfigFile = "/Users/tommylike/.kube/infra-hk.yaml"
kubernetesTemplateFolder = "/Users/tommylike/Work/go/src/github.com/omnibuildplatform/omni-orchestrator/resources/kubernetes_templates"
[persistentStore]
pluginName = "cassandra"
hosts = "127.0.0.1"
port = 9042
keyspace = "omni_orchestrator"
protoVersion = 0