name = "omni-orchestrator"
[server]
httpPort = 8080
[log]
logFile = "./logs/info-{date}.log"
errFile = "./logs/error-{date}.log"
[jobManager]
[jobManager.engine]
[jobManager.persistentStore]

[logManager]
[logManager.engine]
[logManager.persistentStore]