name = "omni-orchestrator"
httpPort = 8080
serverName = "localhost:8080"
[log]
logFile = "./logs/info-{date}.log"
errFile = "./logs/error-{date}.log"

[manager]
dataFolder = "./data"
uploadToken = "316462d0c029ba707ad1"