name = "omni-orchestrator"
[server]
httpPort = 8080
[log]
logFile = "./logs/info-{date}.log"
errFile = "./logs/error-{date}.log"
[jobManager]
worker = 3
syncInterval = 2
[logManager]
worker = 5
[engine]
pluginName = "kubernetes"
configFile = "/Users/tommylike/.kube/infra-test.yaml"
imageTagForOSImageBuild = "tommylike/omni-worker:0.1.4"
OmniRepoAddress = "http://omni-repository.omni-repository.svc.cluster.local/data/upload"
OmniRepoToken = "316462d0c029ba707ad2"
[persistentStore]
pluginName = "cassandra"
hosts = "127.0.0.1"
port = 9042
keyspace = "omni_orchestrator"
protoVersion = 0