definitions:
  app.ApplicationInfo:
    properties:
      commitID:
        type: string
      releaseAt:
        type: string
      tag:
        type: string
    type: object
  application.CreateJobRequest:
    properties:
      domain:
        type: string
      engine:
        type: string
      service:
        type: string
      spec:
        additionalProperties: true
        type: object
      task:
        type: string
      userID:
        type: string
    required:
    - domain
    - engine
    - service
    - spec
    - task
    - userID
    type: object
  common.Job:
    properties:
      detail:
        type: string
      domain:
        type: string
      endTime:
        type: string
      engine:
        type: string
      extraIdentities:
        additionalProperties:
          type: string
        type: object
      id:
        type: string
      service:
        type: string
      spec:
        additionalProperties: true
        type: object
      startTime:
        type: string
      state:
        type: string
      steps:
        items:
          $ref: '#/definitions/common.Step'
        type: array
      task:
        type: string
      userID:
        type: string
      version:
        type: integer
    type: object
  common.Step:
    properties:
      endTime:
        type: string
      id:
        type: integer
      message:
        type: string
      name:
        type: string
      startTime:
        type: string
      state:
        type: string
    type: object
  controller.ApplicationStatus:
    properties:
      info:
        $ref: '#/definitions/app.ApplicationInfo'
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: get application health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ApplicationStatus'
      summary: Application health
      tags:
      - Status
  /jobs:
    delete:
      consumes:
      - application/json
      description: Delete Job with identity
      parameters:
      - description: job service type
        in: query
        name: service
        required: true
        type: string
      - description: job task type
        in: query
        name: task
        required: true
        type: string
      - description: job domain type
        in: query
        name: domain
        required: true
        type: string
      - description: job ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Delete a job
      tags:
      - Job
    get:
      consumes:
      - application/json
      description: Query job status with identity
      parameters:
      - description: job service type
        in: query
        name: service
        required: true
        type: string
      - description: job task type
        in: query
        name: task
        required: true
        type: string
      - description: job domain type
        in: query
        name: domain
        required: true
        type: string
      - description: job ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Job'
      summary: Query Job Status
      tags:
      - Job
    post:
      consumes:
      - application/json
      description: Create a job with specified SPEC
      parameters:
      - description: body for create a job
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/application.CreateJobRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/common.Job'
      summary: Create Job
      tags:
      - Job
  /jobs/logs:
    get:
      consumes:
      - application/json
      description: Query job status with identity
      parameters:
      - description: job service type
        in: query
        name: service
        required: true
        type: string
      - description: job task type
        in: query
        name: task
        required: true
        type: string
      - description: job domain type
        in: query
        name: domain
        required: true
        type: string
      - description: job ID
        in: query
        name: id
        required: true
        type: string
      - description: job StepID
        in: query
        name: stepID
        required: true
        type: string
      - description: Step log start time
        in: query
        name: startTimeUUID
        type: string
      - description: max record to retrieve
        in: query
        name: maxRecord
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      summary: Query Job Logs
      tags:
      - Job
swagger: "2.0"
