apiVersion: batch/v1
kind: Job
metadata:
  name: {{ index . "name" }}
  namespace: {{ index . "namespace" }}
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - echo
            - job succeed
          image: alpine/curl
          imagePullPolicy: Always
          name: job-completed
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - omni-imager
            - --package-list
            - /etc/omni-imager/openEuler-customized.json
            - --config-file
            - /etc/omni-imager/conf.init
            - --build-type
            - {{ index . "format" }}
            - --output-file
            - openEuler-{{ index . "name" }}.iso
          image: tommylike/omni-worker:0.4.0
          imagePullPolicy: IfNotPresent
          name: image-build
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/omni-imager/openEuler-customized.json
              name: {{ index . "name" }}-config
              subPath: openEuler-customized.json
            - mountPath: /etc/omni-imager/conf.init
              name: {{ index . "name" }}-config
              subPath: conf.yaml
            - mountPath: /data/
              name: {{ index . "name" }}-data
          resources:
            requests:
              memory: "20480Mi"
              cpu: "1000m"
            limits:
              memory: "20480Mi"
              cpu: "1000m"
        - command:
            - curl
            - -vvv
            - -FimageFile=@/data/omni-workspace/Customized-{{ index . "name" }}.iso
            - -FchecksumFile=@/data/omni-workspace/Customized-{{ index . "name" }}.iso.sha256sum
            - -Fname={{ index . "name" }}
            - -Falgorithm=sha256
            - -FfileName=Customized-{{ index . "name" }}.iso
            - -FexternalID={{ index . "name" }}
            - -FuserID={{ index . "userID" }}
            - -Fpublish=true
            - -FexternalComponent=omni-orchestrator
            - http://omni-repository.omni-repository.svc.cluster.local:8088/images/upload
          image: alpine/curl
          imagePullPolicy: Always
          name: image-upload
          volumeMounts:
            - mountPath: /data/
              name: {{ index . "name" }}-data
      restartPolicy: Never
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ index . "name" }}
          name: {{ index . "name" }}-config
        - emptyDir:
            sizeLimit: 20G
            medium: Memory
          name: {{ index . "name" }}-data
  ttlSecondsAfterFinished: 1800
